### ISSUE TITLE
MAM Result IQ has wrong from attr when requesting MUCs

### ISSUE THREAD

**Issue by akrherz** [igniterealtime/openfire-monitoring-plugin#18] opened 2019-01-07 03:54 UTC
...Migrated from [Ignite Jira OF-1651](https://issues.igniterealtime.org/projects/OF/issues/OF-1651)

```xml
<!-- Outgoing 08.12.2018 00:08:22 -->
<iq xmlns="jabber:client" to="tikifest2018@conference.wikisuite.net" type="set" id="1a8cfada-d7b3-411f-814e-9c2a2eff01ea" from="test123@wikisuite.net/gajim.G20T95J5">
<query xmlns="urn:xmpp:mam:2" queryid="ce9d95ce-0413-4a07-aa87-958e8a804a69">
<x xmlns="jabber:x:data" type="submit">
<field var="FORM_TYPE" type="hidden">
<value>urn:xmpp:mam:2</value>
</field>
<field var="start" type="text-single">
<value>2018-12-06T23:08:22Z</value>
</field>
</x>
<set xmlns="http://jabber.org/protocol/rsm">
<max>70</max>
</set>
</query>
</iq>
 
<!-- Incoming 08.12.2018 00:08:23 -->
<iq xmlns="jabber:client" type="result" id="1a8cfada-d7b3-411f-814e-9c2a2eff01ea" from="wikisuite.net" to="test123@wikisuite.net/gajim.G20T95J5">
<fin xmlns="urn:xmpp:mam:2" queryid="ce9d95ce-0413-4a07-aa87-958e8a804a69" complete="true">
<set xmlns="http://jabber.org/protocol/rsm">
<count>0</count>
</set>
</fin>
</iq>
```

Testable with the testaccount of https://trunk.wikisuite.net/HomePage

**Comment by guusdk** [comment] 2019-01-17 18:37
The namespace in this request reads "urn:xmpp:mam:2". The most recent version of the monitoring plugin does not support this.

**Comment by guusdk** [comment] 2019-01-17 20:12
@lovetox - you originally reported this issue. Would you mind testing it against conference.igniterealtime.org, which has an up-to-date version of the plugin (but still does not support mam:2).

**Comment by lovetox** [comment] 2019-01-20 11:42
No problem with this server, mam:1 seems to work fine there.

Gajim only uses mam:2 if it is announced on the muc, so this might hint to the problem

**Comment by lovetox** [comment] 2019-01-20 11:45
```
<!-- Incoming 20.01.2019 12:44:20 -->
<iq xmlns="jabber:client" type="result" id="c073a449-e3d9-4150-82c7-16ba7553b911" from="tikifest2018@conference.wikisuite.net" to="test123@wikisuite.net/gajim.G20T95J5">
<query xmlns="http://jabber.org/protocol/disco#info">
<identity category="conference" name="tikifest2018" type="text" />
<feature var="http://jabber.org/protocol/muc" />
<feature var="muc_public" />
<feature var="muc_open" />
<feature var="muc_unmoderated" />
<feature var="muc_nonanonymous" />
<feature var="muc_unsecured" />
<feature var="muc_persistent" />
<feature var="urn:xmpp:mam:0" />
<feature var="urn:xmpp:mam:1" />
<feature var="urn:xmpp:mam:0" />
<feature var="urn:xmpp:mam:1" />
<feature var="urn:xmpp:mam:2" />
<feature var="urn:xmpp:mam:0" />
<feature var="urn:xmpp:mam:1" />
<feature var="urn:xmpp:mam:2" />
<feature var="http://jabber.org/protocol/disco#info" />
<x xmlns="jabber:x:data" type="result">
<field var="FORM_TYPE" type="hidden">
<value>http://jabber.org/protocol/muc#roominfo</value>
</field>
<field var="muc#roominfo_description" label="Description">
<value>Tikifest 2018</value>
</field>
<field var="muc#roominfo_subject" label="Subject">
<value />
</field>
<field var="muc#roominfo_occupants" label="Number of occupants">
<value>8</value>
</field>
<field var="x-muc#roominfo_creationdate" label="Creation date">
<value>2018-09-03T14:41:21.907Z</value>
</field>
</x>
</query>
</iq>
```

**Comment by guusdk** [comment] 2020-12-04 12:33
I'm closing this issue, as I can't reproduce it with any of the recent versions of the Monitoring plugin.

```
<!-- Sent to Openfire 4.7.0 alpha -->
<iq xmlns="jabber:client" to="test@conference.example.org" type="set" id="1">
  <query xmlns="urn:xmpp:mam:2" queryid="2">
    <x xmlns="jabber:x:data" type="submit">
      <field var="FORM_TYPE" type="hidden">
        <value>urn:xmpp:mam:2</value>
      </field>
      <field var="start" type="text-single">
        <value>2018-12-06T23:08:22Z</value>
      </field>
    </x>
    <set xmlns="http://jabber.org/protocol/rsm">
      <max>70</max>
    </set>
  </query>
</iq>


<!-- Response with Monitoring plugin 2.1.0 (indentation mine) -->
<iq type="result" id="1" from="test@conference.example.org" to="john@example.org/octarine">
  <fin xmlns="urn:xmpp:mam:2" queryid="2" complete="true">
    <set xmlns="http://jabber.org/protocol/rsm">
      <count>0</count>
    </set>
  </fin>
</iq>

<!-- Response from Monitoring plugin 2.0.1 -->
<iq type="result" id="1" from="test@conference.example.org" to="john@example.org/octarine"><fin xmlns="urn:xmpp:mam:2" queryid="2"><set xmlns="http://jabber.org/protocol/rsm"><count>0</count></set></fin></iq>

<!-- Response from Monitoring plugin 2.0.0 -->
<iq type="result" id="1" from="test@conference.example.org" to="john@example.org/octarine"><fin xmlns="urn:xmpp:mam:2" queryid="2"><set xmlns="http://jabber.org/protocol/rsm"><count>0</count></set></fin></iq>

<!-- Response from Monitoring plugin 1.8.1 -->
<iq type="result" id="1" from="test@conference.example.org" to="john@example.org/octarine"><fin xmlns="urn:xmpp:mam:2" queryid="2" complete="true"><set xmlns="http://jabber.org/protocol/rsm"><count>0</count></set></fin></iq>
```

**Closed by guusdk** 2020-12-04 12:33 UTC
