### ISSUE TITLE
Monitoring plugin not showing actual messages in search

### ISSUE THREAD

**Issue by akrherz** [igniterealtime/openfire-monitoring-plugin#2] opened 2019-01-04 15:33 UTC
...Migrated from [Ignite Jira OF-1655](https://issues.igniterealtime.org/browse/OF-1655)...

When you do a search for a keyword it shows conversations list, but when you press on one of them it doesn't show actual conversations on the right side. It says "Select a conversation to the left to view details." Rebuilding index doesn't help.

Issue started with 4.3.0 update.

**Comment by suf4dev** [comment] 2019-01-11 23:21
I resolved this issue by adding rome dependency to pom.xml of monitoring plugin. 
<dependency>
            <groupId>rome</groupId>
            <artifactId>rome</artifactId>
            <version>1.0</version>
        </dependency>

**Comment by wrooot** [comment] 2019-01-12 08:44
Can you make a PR with this change or give a more specific example? Thanks

**Comment by wrooot** [comment] 2019-01-12 09:32
I have tried to do the fix you proposed in chat. Will see what others have to say. https://github.com/igniterealtime/openfire-monitoring-plugin/pull/21

**Comment by wrooot** [comment] 2019-01-14 09:44
Fixed with https://github.com/igniterealtime/openfire-monitoring-plugin/commit/762144dbc9e9243831926579e9d529d915263ce3

**Closed** 2019-01-14 09:44 UTC

**Comment by wrooot** [comment] 2019-01-14 09:46
1.7.0 release

**Comment by guusdk** [comment] 2021-12-09 08:22
I've long wondered _why_ Rome is needed to fix this.

This is in turned caused by a missing dependency for thecom.sun.syndication.io.FeedException class, which is part of the ROME framework for RSS and Atom feeds. It is needed by the com.sun.jersey.atom.rome.impl.provider.entity.AtomFeedProvider class in Jersey.

See https://stackoverflow.com/a/42728310/189203 for details.
