### ISSUE TITLE
MAM does not work for federated users

### ISSUE THREAD

**Issue by akrherz** [igniterealtime/openfire-monitoring-plugin#17] opened 2019-01-07 03:48 UTC
...Migrated from [Ignite Jira OF-1546](https://issues.igniterealtime.org/projects/OF/issues/OF-1546)...

The MAM implementation ties things to the local client session, which obviously won't work for users that join a muc via s2s. 

Either we should not advertise MAM to them, or we should make things work properly.

**Comment by guusdk** [comment] 2019-01-17 19:47
This was a duplicate of OF-1644, which has been fixed in version 1.7.0 of the Monitoring plugin.

**Closed by guusdk** 2019-01-17 19:47 UTC
